services:
  mlflow:
    build: ./mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow

  prefect:
    build: ./prefect
    ports:
      - "4200:4200"
    volumes:
      - prefect_data:/prefect
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_URL=http://0.0.0.0:4200/api

volumes:
  mlflow_data:
  prefect_data:
